### ISSUE TITLE
Fides does not find the correct solution fo a simple sum of squares problem with binding bounds

### ISSUE THREAD

**Issue by roecla** [fides-dev/fides#43]
When minimizing a simple sum of squares function with partially binding bounds, fides fails to find the correct solution. It correctly converges to the boundaries in the dimensions where the bounds are binding but fails in the dimension without bounds. Instead of converging to setting x to 0 in that dimension, it converges to 0.59. 

The convergence message is: 
> Stopping as function difference 9.77E-15 was smaller than specified tolerances (atol=1.00E-08, rtol=1.00E-08)

Here is a minimal working example: 

```python3

from fides import Optimizer
import numpy as np
from fides import BFGS


def sum_of_squares(x):
    """Return function value and gradient of the sum of squares function."""
    fval = (x ** 2).sum()
    gradient = 2 * x
    return fval, gradient


lower_bounds = np.array([1, -np.inf, -np.inf])
upper_bounds = np.array([np.inf, np.inf, -1])
start_x = np.array([3, 2, -3])

true_solution = np.array([1, 0, -1])

opt = Optimizer(
    fun=sum_of_squares,
    lb=lower_bounds,
    ub=upper_bounds,
    hessian_update=BFGS(),
    resfun=False,
)

res = opt.minimize(start_x)

# Fides believes to have found the minimum
assert opt.converged

# fides_solution is [1.0000000000000233, 0.59204316173441, -1.0000000000000233]
fval, fides_solution, grad, hess = res
```

fides version: 0.6.3

**Comment by FFroehlich** [comment]
Hi @roecla,

thanks for your interest in fides and reporting this, I will have a look into it. While the algorithm does work with boundaries, it requires that the optimum is away from the boundary for theoretically guaranteed convergence and in my experience it also causes trouble in practice. Nevertheless, this is a nice small scale example to investigate possible remedies.

**Comment by FFroehlich** [comment]
After some testing, I found that the truncation stepback strategy helps a lot for this problem. The truncation strategy truncates the search direction at the boundary instead of reflecting it. You can activate the truncation strategy by passing
```
options={
    fides.Options.STEPBACK_STRAT: fides.StepBackStrategy.TRUNCATE
}
```
as argument when instantiating the optimizer. I hope this helps.

Optimization performance also improves when providing the Gauss-Newton approximation to the Hessian (in this case simply `2 * np.eye(len(x))`). In my experience, the BFGS updating scheme fails to provide good updates close to the boundary (or does not update at all as the curvature condition is not met), which also seems to be happening with this problem.

**Comment by roecla** [comment]
Hi @FFroehlich, thank you for the swift and in depth response! That was very helpful and insightful. Your suggestion to use the "truncate" step back strategy solves the problem. :+1:
