### ISSUE TITLE
Reduce logging

### ISSUE THREAD

**Issue by yannikschaelte** [fides-dev/fides#50]
Many logging events are on level warning or info. I was wondering whether one wants to downgrade these one step, such that most are info or debug. Reason: In multistart settings, the generated output is rather long.

Alternatively, we would simply set the default log level for e.g. fides in pypesto to error or warning.

**Comment by FFroehlich** [comment]
Most logging events are at the info level and it doesn't make sense to push that to debug since debug log is quite bulky. 

Only termination messages are at the warning level, pushing that to info would mean not being able to have a single line summary per start vs full history.

If you don't want any logging by default the best option is to set the default to error.

**Comment by yannikschaelte** [comment]
ok, would consider that then in pypesto, to make it consistent with e.g. scipy.
